//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahaWikiAPI.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class content
    {
        public string uncKey { get; set; }
        public string ansiKey { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string AKA { get; set; }
        public string usageRegion { get; set; }
        public string notes { get; set; }
    }
}
